triggers:
- description: null
  envs: []
  last_enabled_at: 2024-08-19 17:17:10.955838+00:00
  name: autumn bird
  pipeline_uuid: game_behaviour_prediction
  schedule_interval: '@once'
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-08-18 17:04:00+00:00
  status: active
  token: 1685139a59ad49c397f81af246338bd5
  variables: {}
